; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Sep 01 2020 15:50:35 GMT+0200 (Středoevropský letní čas)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


