; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Tue Sep 01 2020 15:50:36 GMT+0200 (Středoevropský letní čas)
M280 P0 S90 ; retract BLTouch

